apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      name: docker-registry
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
