apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: shuttle
type: Opaque
data:
  DB_URL: cG9zdGdyZXM6Ly9zaHV0dGxlOnNlY3JldEBkYi1jbHVzdGVyLXJ3LnNodXR0bGUuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9zaHV0dGxl
