apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: kafka
  interval: 1m
  values:
    image:
      tag: 0.49.1-amd64
