apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: kafka
  interval: 30s
  values:
    global:
      security:
        allowInsecureImages: true
      imageRegistry: docker.arvancloud.ir
    controller:
      replicaCount: 1
