apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: default
spec:
  chart:
    spec:
      chart: infisical-standalone
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: infisical
      version: "*"
  interval: 1m0s
#  values:
#    infisical:
#      image:
#        repository: infisical/infisical
#        tag: "0.54.6"
#        pullPolicy: IfNotPresent
