#apiVersion: v1
#kind: Secret
#metadata:
#  name: infisical-secrets
#type: Opaque
#stringData:
#  ENCRYPTION_KEY: "2d1efb7c68ecfbc94b015a9c29803dfd"
#  AUTH_SECRET: "NJi00wld3B83ETUKw9YjztuqXEOfRjL0+sbSWgBtCJs="
#  SITE_URL: "http://localhost"
