apiVersion: batch/v1
kind: Job
metadata:
  name: blogo
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/force: Enabled
spec:
  template:
    spec:
      containers:
        - name: blogo
          image: sadrasamadi/blogo
          imagePullPolicy: Always
          command: [ "sh", "-c", "./main sync" ]
          envFrom:
            - configMapRef:
                name: blogo
      restartPolicy: Never
  backoffLimit: 3
