apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  ENCRYPTION_KEY: "3024e4dd395e89cade12ff13d2ea44cc"
  AUTH_SECRET: "om7UPCQXuzolBmvtei5x5b6Pp2zcVuyp+y+7KGKIjN4="
  SITE_URL: "https://infisical.shuttle.sadra.xyz"
#  DB_CONNECTION_URI: <>
#  REDIS_URL: <>
