apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - namespace.yaml
  - image-update-automation.yaml
  - ../../components/postgres-db
  - ../../components/redis
  - ../../components/backend
  - ../../components/frontend
images:
  - name: sadrasamadi/shuttle-backend
    newTag: latest
    digest: sha256:d0cc399c66d0717fa47619f9f99b742d2b3a2063f9c038dfaa098b0ee43d3ddd # {"$imagepolicy": "dev:backend:digest"}
  - name: sadrasamadi/shuttle-frontend
    newTag: latest
    digest: sha256:631a8e8a3a6533d4fdc1810c019be708cfad4cf2c88ff7d7ef54d58be33d7f79 # {"$imagepolicy": "dev:frontend:digest"}
patches:
  - target:
      kind: IngressRouteTCP
      name: redis
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: HostSNI(`dev.redis.shuttle.sadra.xyz`)
  - path: backend.secret.yaml
  - target:
      kind: IngressRoute
      name: backend
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: Host(`dev.api.shuttle.sadra.xyz`)
  - path: frontend.config-map.yaml
  - target:
      kind: IngressRoute
      name: frontend
    patch: |
      - op: replace
        path: /spec/routes/0/match
        value: Host(`dev.app.shuttle.sadra.xyz`)
