apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: default
stringData:
  postgres_url: "postgres://shuttle:secret@postgres-rw.shared.svc.cluster.local:5432/shuttle"
  redis_url: "redis://default:secret@redis-master.prod.svc.cluster.local:6379/0"
