apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres
  namespace: shared
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`shared.postgres.shuttle.sadra.xyz`)
      services:
        - name: postgres-rw
          port: 5432
  tls:
    certResolver: letsencrypt
