apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`default.app.shuttle.sadra.xyz`)
      kind: Rule
      services:
        - name: frontend
          port: 80
  tls:
    certResolver: letsencrypt
