apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sadrasamadi/shuttle-frontend
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/assets
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: frontend
