apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sadrasamadi/shuttle-backend:latest@sha256:bdb6958849b062d51f429255bc2345b2d670618390d31b600240e54110592349
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
