apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: shared
type: Opaque
stringData:
  postgres_url: "postgres://shuttle:secret@postgres-rw.shared.svc.cluster.local:5432/shuttle"
  redis_url: "redis://default:secret@redis-master.shared.svc.cluster.local:16379/0"
