apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shuttle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sadrasamadi/shuttle-frontend:latest@sha256:c7084b6b3906dd1d304961f2d1fc09a0720afd8390cd48a8db7289241c286268 # {"$imagepolicy": "shuttle:frontend"}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/assets
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: frontend
