apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    certificatesResolvers:
      le:
        acme:
          email: info@shuttle.sadra.xyz
          storage: /data/acme.json
          httpChallenge:
            entryPoint: web
    persistence:
      enabled: true
      size: 1Gi
    ports:
      postgres:
        port: ':5432'
      redis:
        port: ':6379'
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.shuttle.sadra.xyz`)
        entryPoints:
          - websecure
