apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shuttle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sadrasamadi/shuttle-backend:latest@sha256:26c86d4bfe48f9d3b7f97e4c7b8936bf4cba75f6d677506e2e7f5370dfbdaeb8 # {"$imagepolicy": "shuttle:backend"}
          imagePullPolicy: Always
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_URL
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
