apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shuttle
  labels:
    app: backend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sadrasamadi/shuttle-backend:234bc518cb0f5916d691a2224ef2ca029f091967
          imagePullPolicy: Always
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_URL
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
