apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shuttle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sadrasamadi/shuttle-backend:latest@sha256:a68c6a7d9b888e9321dbec9ac5777156cecb22ecc01ed3894c4dddb0aa7d4941 # {"$imagepolicy": "shuttle:backend"}
          imagePullPolicy: Always
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_URL
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
