apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend
  namespace: shuttle
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.sadra.xyz`)
      kind: Rule
      services:
        - name: backend
          port: 80
