apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shuttle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sadrasamadi/shuttle-backend:latest@sha256:ef1cce2ef1c7b0bf4d8c22cf71e9448c5d4cfce7435898112d99a215fa53042d # {"$imagepolicy": "shuttle:backend"}
          imagePullPolicy: Always
          env:
            - name: POSTGRES
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: POSTGRES
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
