apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: shuttle
type: Opaque
data:
  DB_URL: cG9zdGdyZXM6Ly9zaHV0dGxlOnNlY3JldEBkYXRhYmFzZS1ydy5zaHV0dGxlLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvc2h1dHRsZQ==
