apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: default
type: Opaque
stringData:
  postgres_url: "postgres://shuttle:secret@postgres-rw.default.svc.cluster.local:5432/shuttle"
  redis_url: "redis://default:secret@redis-master.default.svc.cluster.local:6379/0"
