apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: shuttle
type: Opaque
data:
  POSTGRES: cG9zdGdyZXM6Ly9zaHV0dGxlOnNlY3JldEBwb3N0Z3Jlcy1ydy5zaHV0dGxlLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvc2h1dHRsZQ==
  REDIS: cmVkaXM6Ly9kZWZhdWx0OnNlY3JldEByZWRpcy1tYXN0ZXIuc2h1dHRsZS5zdmMuY2x1c3Rlci5sb2NhbDoxNjM3OS8w
