name: Build and Push Frontend Docker

on:
  push:
    branches:
      - main
    paths:
      - 'apps/frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd apps/frontend
          TS=$(date +%Y%m%d%H%M%S)
          docker build -t sadrasamadi/shuttle-frontend:$TS .
          docker push sadrasamadi/shuttle-frontend:$TS
