apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: shuttle
spec:
  chartRef:
    kind: OCIRepository
    name: redis
  interval: 1m0s
  values:
    architecture: standalone
    auth:
      existingSecret: redis
      existingSecretPasswordKey: password
    master:
      persistence:
        enabled: false
