apiVersion: v1
kind: Namespace
metadata:
  name: swfs-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: swfs
  namespace: swfs-system
spec:
  interval: 24h
  url: https://seaweedfs.github.io/seaweedfs-operator/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: swfs
  namespace: swfs-system
spec:
  chart:
    spec:
      chart: seaweedfs-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: swfs
      version: '0.1.9'
  interval: 24h
